name: Full Research Project CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_TYPE: Release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          wget \
          python3-dev \
          python3-pip \
          libhdf5-dev \
          libboost-all-dev \
          gfortran

    - name: Install Python Packages
      run: |
        pip3 install numpy matplotlib mpi4py

    - name: Build OpenMPI from Source
      run: |
        sudo apt-get purge -y libopenmpi-dev openmpi-bin || true
        wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.5.tar.gz
        tar -xzf openmpi-4.1.5.tar.gz
        cd openmpi-4.1.5
        ./configure --prefix=$HOME/openmpi --enable-mpi-cxx
        make -j$(nproc)
        make install
        echo "$HOME/openmpi/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/openmpi/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build and Install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        mkdir -p kokkos/build
        cd kokkos/build
        cmake .. \
          -DCMAKE_CXX_COMPILER=$HOME/openmpi/bin/mpic++ \
          -DKokkos_ENABLE_OPENMP=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DCMAKE_INSTALL_PREFIX=$HOME/kokkos-install
        make -j$(nproc)
        make install

    - name: Build and Install ADIOS2
      run: |
        git clone https://github.com/ornladios/ADIOS2.git
        cd ADIOS2
        git checkout v2.10.1
        mkdir -p build
        cd build
        cmake .. \
          -DADIOS2_USE_MPI=OFF \
          -DADIOS2_USE_Python=ON \
          -DADIOS2_BUILD_BINDINGS=ON \
          -DCMAKE_INSTALL_PREFIX=$HOME/adios2-install
        make -j$(nproc)
        make install

    - name: Build and Install Sundials 
      run: |
        git clone https://github.com/LLNL/sundials
        cd sundials
                mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_INSTALL_PREFIX=$HOME/sundials-install \
          -DBUILD_SHARED_LIBS=ON \
          -DSUNDIALS_ENABLE_CXX=ON \
          -DSUNDIALS_ENABLE_C=ON \
          -DSUNDIALS_EXAMPLES_ENABLE=OFF \
          -DSUNDIALS_TESTS_ENABLE=OFF
        make -j$(nproc)
        make install
        

    - name: Clone Catch2
      run: |
        mkdir -p externals
        cd externals
        git clone https://github.com/catchorg/Catch2.git

    - name: Configure CMake Project
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_CXX_COMPILER=$HOME/openmpi/bin/mpic++ \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$HOME/kokkos-install;$HOME/adios2-install;$HOME/sundials-install" \
          -DADIOS2_DIR=$HOME/adios2-install/lib/cmake/adios2

    - name: Build Project
      run: |
        cd build
        make -j$(nproc)

    - name: Run Catch2 C++ Tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Run Python Post-Processing
      run: |
        export PYTHONPATH=$HOME/adios2-install/lib/python3.10/site-packages:$PYTHONPATH
        python3 your_python_script.py
